POST http://localhost:4004/odata/v4/sales-catalog/SalesCatalogService.postSalesOrder
Content-Type: application/json

{
    "senderMail": "jibin.thomas@msitek.us",
    "dmsFolder": "spa-res:cmis:folderid:21nAH28UCgzjqrMxId5gHaz2lm_dixsOPig8RLtWatQ"
}