POST http://localhost:4004/odata/v4/inv-catalog/InvCatalogService.postSalesOrder
Content-Type: application/json
{
    "senderMail": "jibin.thomas@msitek.us",
    "dmsFolder": "'spa-res:cmis:folderid:Fdvrdglf5AsxXWbToXHc7EGXDgXa_PVW3bnN3ErRwOE'"
}